image: docker:latest

stages:
- build
- deploy

before_script:
- echo "$CI_REGISTRY"
- echo "$CI_REGISTRY_USER"
- echo "$CI_REGISTRY_PASSWORD"
- echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin

variables:
  DOCKER_IMAGE_NAME: pos-assistant
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"

services:
  - docker:dind

build:
  stage: build
  script:
    - docker build --pull -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push $DOCKER_IMAGE_NAME