stages:
- build

build:
  # Use the official docker image for building Docker images.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "Logging in to Docker registry..."
    - docker login -u martinignacioriosc@gmail.com -p Martin212.365 $CI_REGISTRY
  script:
    - echo "Building Docker image..."
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_SHA
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - echo "Pushing Docker image..."
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

  # Run this job only if a Dockerfile exists
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile