image: docker:dind

stages:
- build
- deploy

variables:
  DOCKER_IMAGE_NAME: pos-assistant

build:
  stage: build
  script:
    - docker build --pull -t $DOCKER_IMAGE_NAME .

deploy:
  stage: deploy
  only:
    - master
  script:
    - docker push $DOCKER_IMAGE_NAME