export enum ProjectStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  QA = 'QA',
  COMPLETED = 'COMPLETED',
  DELIVERED = 'DELIVERED',
  BLOCKED = 'BLOCKED',
  BUG_FIXING = 'BUG_FIXING',
  UPDATING = 'UPDATING',
  SUSPENDED = 'SUSPENDED'
}